### ISSUE TITLE
Page lock error caused by the plugin

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [cosmocode/clearhistory#7]
With the plugin, there is the strange phenomenon under PHP8 that wiki pages are locked by someone, although they were not in change mode at all, but wanted to display these pages. 
In this context, it is noticeable that even in the display mode of a wiki page, several lock entries are created in the "locks" directory, which are no longer deleted when the page is exited.
Furthermore, pages are often not locked even though they are open for editing.

**Comment by splitbrain** [comment]
I assume this happens with autoclear enabled only?

**Comment by Juergen-aus-Zuendorf** [comment]
It was very difficult to reproduce. I think I had the standard configuration. But I've cleared the history manually additionally again and again at irregular intervals.

**Comment by splitbrain** [comment]
I think this might have been caused by #6 as it threw an error after locking the page and then never unlocking it.
